#:kivy 1.11.0

<StackLayout>:
	orientation: "lr-tb"
	spacing: 10
	padding: 10

	Button:
		text: "1st"
		size_hint: None, .15
		width: 100

	Button:
		text: "2nd"
		size_hint: None, .15
		width: 120

	Button:
		text: "3rd"
		size_hint: None, .15
		width: 140

	Button:
		text: "4th"
		size_hint: None, .15
		width: 160

	Button:
		text: "5th"
		size_hint: None, .15
		width: 180

	Button:
		text: "6th"
		size_hint: None, .15
		width: 200